name: Docker Actions

on:
  pull_request:
    types: [labeled]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: hello-action
        uses: ./.github/actions/hello-world

      - name: meow
        uses: ./.github/actions/cat-facts
        id: cat

      # - name: create-issue
      #   uses: ./.github/actions/issue-maker
      #   with:
      #     repoToken: ${{secrets.GITHUB_TOKEN}}
      #     catFact: ${{steps.cat.outputs.fact}}
      #     issueTitle: "a cat fact for you"

      - name: soliciatr saludo
        uses:  ./.github/actions/jsaction  
        id: solicitarsaludo
        with:
          who-to-greet: 'Andres .. '

      - name: script
        runs: |
          echo ${{steps.solicitarsaludo.outputs.time}}